#!/bin/bash
# This hook is run after this virtualenv is activated.

export PYTHONPATH=$WORKON_HOME/pygly/src
export PYTHONPATH=$WORKON_HOME/pygly/src/contrib/pyrr:$PYTHONPATH
export PYTHONPATH=$WORKON_HOME/pygly/src/contrib/pyglet:$PYTHONPATH
export PYTHONPATH=$WORKON_HOME/pygly/src/contrib/pyglfw:$PYTHONPATH
