[build-system]
requires = [
    "setuptools>=69.4.0",
    # see https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice
    "numpy>=2.0.0",
    "setuptools_scm[toml]>=8.1",
    "Cython>=3.0.0"
]

[tool.setuptools_scm]
write_to = "vispy/version.py"
local_scheme = "dirty-tag"


[tool.cibuildwheel]
skip = "pp* *-win32 *-manylinux_i686 *-musllinux*"
test-command = "python -c \"import vispy; vispy.test('nobackend')\""
test-extras = ["test"]


[tool.cibuildwheel.linux]
before-all = [
    "yum install -y fontconfig || apk add fontconfig-dev jpeg-dev; pip install freetype-py",
]

[tool.cibuildwheel.windows]
environment = {FREETYPEPY_BUNDLE_FT=1}

[tool.pixi.workspace]
name = "vispy"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tool.pixi.dependencies]
numpy = "*"
freetype-py = "*"
hsluv = "*"
kiwisolver = "*"
packaging = "*"

[tool.pixi.pypi-dependencies]
vispy = { path = ".", editable = true }

[tool.pixi.feature.test.dependencies]
coveralls = "*"
cython = "*"
pytest = "*"
pytest-sugar = "*"
pytest-cov = "*"
meshio = "*"
pillow = "*"
imageio = "*"
sphinx-gallery = "*"
scipy = "*"
networkx = "*"

[tool.pixi.feature.min.dependencies]
numpydoc = "*"

[tool.pixi.feature.osmesa]
platforms = ["linux-64"]

[tool.pixi.feature.osmesa.dependencies]
libglu = "*"
mesalib = ">=25.0.5,<25.1.0"

[tool.pixi.feature.full.dependencies]
cmake = "*"
decorator = "*"
glfw = "!=3.3.1"
jupyter = "*"
jupyter-rfb = "*"
matplotlib-base = "*"
pyopengl = "*"
scikit-image = "*"

[tool.pixi.feature.docs.dependencies]
numpydoc = "*"
sphinx = "*"
sphinx-bootstrap-theme = "*"
sphinxcontrib-apidoc = "*"
myst-parser = "*"
pydata-sphinx-theme = "!=0.10.*"

# Vispy backends
[tool.pixi.feature.qt5.dependencies]
pyqt = "5.*"
[tool.pixi.feature.qt6.dependencies]
pyqt6 = "*"
[tool.pixi.feature.sdl2.pypi-dependencies]
pysdl2 = "*"

# Python versions
[tool.pixi.feature.py310.dependencies]
python = "3.10.*"
[tool.pixi.feature.py312.dependencies]
python = "3.12.*"
[tool.pixi.feature.py314.dependencies]
python = "3.14.*"
python-gil = "*"

[tool.pixi.environments]
website = ["py310", "test", "full", "docs"]
py310-min = ["py310", "min", "test"]
py310-osmesa = ["py310", "osmesa", "test"]
py310-full = ["py310", "test", "full", "qt5", "sdl2"]
py310-newqt = ["py310", "test", "full", "qt6", "sdl2"]
py312-full = ["py312", "test", "full", "qt5", "sdl2"]
py312-newqt = ["py312", "test", "full", "qt6", "sdl2"]
py314-full = ["py314", "test", "full", "qt5", "sdl2"]
py314-newqt = ["py314", "test", "full", "qt6", "sdl2"]

[tool.pytest.ini_options]
norecursedirs = [
    ".*",
    "build",
    "dist",
    "CVS",
    "_darcs",
    "arch",
    "*.egg",
    "venv",
    "js",
]