"""

THIS CODE IS AUTO-GENERATED. DO NOT EDIT.

Constants for OpenGL ES 2.0.

"""

from __future__ import division

from . import _GL_ENUM


GL_ALPHA8 = _GL_ENUM('GL_ALPHA8', 32828)
GL_BUFFER_ACCESS = _GL_ENUM('GL_BUFFER_ACCESS', 35003)
GL_BUFFER_MAPPED = _GL_ENUM('GL_BUFFER_MAPPED', 35004)
GL_BUFFER_MAP_POINTER = _GL_ENUM('GL_BUFFER_MAP_POINTER', 35005)
GL_DEPTH24_STENCIL8 = _GL_ENUM('GL_DEPTH24_STENCIL8', 35056)
GL_DEPTH24_STENCIL8 = _GL_ENUM('GL_DEPTH24_STENCIL8', 35056)
GL_DEPTH_COMPONENT16 = _GL_ENUM('GL_DEPTH_COMPONENT16', 33189)
GL_DEPTH_COMPONENT24 = _GL_ENUM('GL_DEPTH_COMPONENT24', 33190)
GL_DEPTH_COMPONENT32 = _GL_ENUM('GL_DEPTH_COMPONENT32', 33191)
GL_DEPTH_COMPONENT32 = _GL_ENUM('GL_DEPTH_COMPONENT32', 33191)
GL_DEPTH_STENCIL = _GL_ENUM('GL_DEPTH_STENCIL', 34041)
GL_DEPTH_STENCIL = _GL_ENUM('GL_DEPTH_STENCIL', 34041)
GL_EGL_image = _GL_ENUM('GL_EGL_image', 1)
GL_EGL_image_external = _GL_ENUM('GL_EGL_image_external', 1)
GL_ETC1_RGB8 = _GL_ENUM('GL_ETC1_RGB8', 36196)
GL_FRAGMENT_SHADER_DERIVATIVE_HINT = _GL_ENUM(
    'GL_FRAGMENT_SHADER_DERIVATIVE_HINT',
    35723)
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET = _GL_ENUM(
    'GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET',
    36052)
GL_FRAMEBUFFER_UNDEFINED = _GL_ENUM('GL_FRAMEBUFFER_UNDEFINED', 33305)
GL_HALF_FLOAT = _GL_ENUM('GL_HALF_FLOAT', 36193)
GL_INT_10_10_10_2 = _GL_ENUM('GL_INT_10_10_10_2', 36343)
GL_LUMINANCE4_ALPHA4 = _GL_ENUM('GL_LUMINANCE4_ALPHA4', 32835)
GL_LUMINANCE8 = _GL_ENUM('GL_LUMINANCE8', 32832)
GL_LUMINANCE8_ALPHA8 = _GL_ENUM('GL_LUMINANCE8_ALPHA8', 32837)
GL_MAX_3D_TEXTURE_SIZE = _GL_ENUM('GL_MAX_3D_TEXTURE_SIZE', 32883)
GL_NUM_PROGRAM_BINARY_FORMATS = _GL_ENUM(
    'GL_NUM_PROGRAM_BINARY_FORMATS',
    34814)
GL_PALETTE4_R5_G6_B5 = _GL_ENUM('GL_PALETTE4_R5_G6_B5', 35730)
GL_PALETTE4_RGB5_A1 = _GL_ENUM('GL_PALETTE4_RGB5_A1', 35732)
GL_PALETTE4_RGB8 = _GL_ENUM('GL_PALETTE4_RGB8', 35728)
GL_PALETTE4_RGBA4 = _GL_ENUM('GL_PALETTE4_RGBA4', 35731)
GL_PALETTE4_RGBA8 = _GL_ENUM('GL_PALETTE4_RGBA8', 35729)
GL_PALETTE8_R5_G6_B5 = _GL_ENUM('GL_PALETTE8_R5_G6_B5', 35735)
GL_PALETTE8_RGB5_A1 = _GL_ENUM('GL_PALETTE8_RGB5_A1', 35737)
GL_PALETTE8_RGB8 = _GL_ENUM('GL_PALETTE8_RGB8', 35733)
GL_PALETTE8_RGBA4 = _GL_ENUM('GL_PALETTE8_RGBA4', 35736)
GL_PALETTE8_RGBA8 = _GL_ENUM('GL_PALETTE8_RGBA8', 35734)
GL_PROGRAM_BINARY_FORMATS = _GL_ENUM('GL_PROGRAM_BINARY_FORMATS', 34815)
GL_PROGRAM_BINARY_LENGTH = _GL_ENUM('GL_PROGRAM_BINARY_LENGTH', 34625)
GL_REQUIRED_TEXTURE_IMAGE_UNITS = _GL_ENUM(
    'GL_REQUIRED_TEXTURE_IMAGE_UNITS',
    36200)
GL_RGB565 = _GL_ENUM('GL_RGB565', 36194)
GL_RGB5_A1 = _GL_ENUM('GL_RGB5_A1', 32855)
GL_RGB8 = _GL_ENUM('GL_RGB8', 32849)
GL_RGBA4 = _GL_ENUM('GL_RGBA4', 32854)
GL_RGBA8 = _GL_ENUM('GL_RGBA8', 32856)
GL_SAMPLER_3D = _GL_ENUM('GL_SAMPLER_3D', 35679)
GL_SAMPLER_EXTERNAL = _GL_ENUM('GL_SAMPLER_EXTERNAL', 36198)
GL_STENCIL_INDEX1 = _GL_ENUM('GL_STENCIL_INDEX1', 36166)
GL_STENCIL_INDEX4 = _GL_ENUM('GL_STENCIL_INDEX4', 36167)
GL_TEXTURE_3D = _GL_ENUM('GL_TEXTURE_3D', 32879)
GL_TEXTURE_BINDING_3D = _GL_ENUM('GL_TEXTURE_BINDING_3D', 32874)
GL_TEXTURE_BINDING_EXTERNAL = _GL_ENUM('GL_TEXTURE_BINDING_EXTERNAL', 36199)
GL_TEXTURE_EXTERNAL = _GL_ENUM('GL_TEXTURE_EXTERNAL', 36197)
GL_TEXTURE_WRAP_R = _GL_ENUM('GL_TEXTURE_WRAP_R', 32882)
GL_UNSIGNED_INT_10_10_10_2 = _GL_ENUM('GL_UNSIGNED_INT_10_10_10_2', 36342)
GL_UNSIGNED_INT_24_8 = _GL_ENUM('GL_UNSIGNED_INT_24_8', 34042)
GL_UNSIGNED_INT_24_8 = _GL_ENUM('GL_UNSIGNED_INT_24_8', 34042)
GL_VERTEX_ARRAY_BINDING = _GL_ENUM('GL_VERTEX_ARRAY_BINDING', 34229)
GL_WRITE_ONLY = _GL_ENUM('GL_WRITE_ONLY', 35001)
GL_compressed_ETC1_RGB8_texture = _GL_ENUM(
    'GL_compressed_ETC1_RGB8_texture',
    1)
GL_compressed_paletted_texture = _GL_ENUM('GL_compressed_paletted_texture', 1)
GL_depth24 = _GL_ENUM('GL_depth24', 1)
GL_depth32 = _GL_ENUM('GL_depth32', 1)
GL_depth_texture = _GL_ENUM('GL_depth_texture', 1)
GL_element_index_uint = _GL_ENUM('GL_element_index_uint', 1)
GL_fbo_render_mipmap = _GL_ENUM('GL_fbo_render_mipmap', 1)
GL_fragment_precision_high = _GL_ENUM('GL_fragment_precision_high', 1)
GL_get_program_binary = _GL_ENUM('GL_get_program_binary', 1)
GL_mapbuffer = _GL_ENUM('GL_mapbuffer', 1)
GL_packed_depth_stencil = _GL_ENUM('GL_packed_depth_stencil', 1)
GL_required_internalformat = _GL_ENUM('GL_required_internalformat', 1)
GL_rgb8_rgba8 = _GL_ENUM('GL_rgb8_rgba8', 1)
GL_standard_derivatives = _GL_ENUM('GL_standard_derivatives', 1)
GL_stencil1 = _GL_ENUM('GL_stencil1', 1)
GL_stencil4 = _GL_ENUM('GL_stencil4', 1)
GL_surfaceless_context = _GL_ENUM('GL_surfaceless_context', 1)
GL_texture_3D = _GL_ENUM('GL_texture_3D', 1)
GL_texture_float = _GL_ENUM('GL_texture_float', 1)
GL_texture_float_linear = _GL_ENUM('GL_texture_float_linear', 1)
GL_texture_half_float = _GL_ENUM('GL_texture_half_float', 1)
GL_texture_half_float_linear = _GL_ENUM('GL_texture_half_float_linear', 1)
GL_texture_npot = _GL_ENUM('GL_texture_npot', 1)
GL_vertex_array_object = _GL_ENUM('GL_vertex_array_object', 1)
GL_vertex_half_float = _GL_ENUM('GL_vertex_half_float', 1)
GL_vertex_type_10_10_10_2 = _GL_ENUM('GL_vertex_type_10_10_10_2', 1)
